export const FETCH_QUIZES_START = 'FETCH_QUIZES_START'
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'
export const FINISH_QUIZ = 'FINISH_QUIZ'
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION'
export const QUIZ_RETRY = 'QUIZ_RETRY'

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION'
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_TOTAL_COUNT_USERS = 'SET_TOTAL_COUNT_USERS'

export const FETCH_RESULTS_TEST_START = 'FETCH_RESULTS_TEST_START'
export const FETCH_RESULTS_TEST_SUCCESS = 'FETCH_RESULTS_TEST_SUCCESS'
export const FETCH_RESULTS_TEST_ERROR = 'FETCH_RESULTS_TEST_ERROR'

export const SET_CURRENT_PAGE_RESULTS = 'SET_CURRENT_PAGE_RESULTS'
export const SET_TOTAL_COUNT_RESULTS = 'SET_TOTAL_COUNT_RESULTS'